# -*- coding: utf-8 -*-
"""EMAIL SPAM CLASSIFICATION PROJECT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ldRQl2--OYn6m64EX8NxwZGKGD5lst0p
"""

#import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df1 = pd.read_csv('emails.csv')
df1

df1.shape

df1.head(5)

df1.tail(5)

#check for null values ('NAN')

df1.isnull().sum()

df1.describe()

#df1.corr()

x = df1.iloc[:, 1:3001].values
y = df1.iloc[:, -1].values
print(x.shape, y.shape)

print(x)

print(y)

#train test split the data:

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

print(x_train)

print(y_train)

print(x_test)

print(y_test)

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
classifier = MultinomialNB()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
print("Accuracy Score for Naive Bayes : ", accuracy_score(y_test,y_pred))

from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(x_train, y_train)
y_pred1 = classifier.predict(x_test)
print("Accuracy Score for SVC : ", accuracy_score(y_pred1,y_test))

